server:
  port: 8081

spring:
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.93.139:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.109.60.208/test
    username: root
    password: "@HWF20020622456@"
mybatis:

  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



